version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    command: mongod --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - '27017'

  app:
    build:
      dockerfile: Dockerfile.compose
      context: ./
    depends_on:
      - mongo
    ports:
      - '3000:3000'
      - '8080:8080'
    environment:
      NODE_ENV: development
      VITE_BASE_SERVER_URL_DEV: ${VITE_BASE_SERVER_URL_DEV}
      VITE_BASE_SERVER_URL_PROD: ${VITE_BASE_SERVER_URL_PROD}
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
      VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
      VITE_EMAIL_DOMAIN_NAME: ${VITE_EMAIL_DOMAIN_NAME}
      BASE_SERVER_URL_DEV: ${BASE_SERVER_URL_DEV}
      BASE_SERVER_URL_PROD: ${BASE_SERVER_URL_PROD}
      SLACK_BOT_TOKEN_DEV: ${SLACK_BOT_TOKEN_DEV}
      SLACK_BOT_TOKEN_PROD: ${SLACK_BOT_TOKEN_PROD}
      CODEPOCKET_CHANNEL_ID_DEV: ${CODEPOCKET_CHANNEL_ID_DEV}
      CODEPOCKET_CHANNEL_ID_PROD: ${CODEPOCKET_CHANNEL_ID_PROD}
      CHAPTER_FRONTED_CHANNEL_ID_DEV: ${CHAPTER_FRONTED_CHANNEL_ID_DEV}
      CHAPTER_FRONTED_CHANNEL_ID_PROD: ${CHAPTER_FRONTED_CHANNEL_ID_PROD}
      MONGO_DB_URI_DEV: ${MONGO_DB_URI_DEV}
      MONGO_DB_URI_PROD: ${MONGO_DB_URI_PROD}
      MONGO_DB_NAME_DEV: ${MONGO_DB_NAME_DEV}
      MONGO_DB_NAME_PROD: ${MONGO_DB_NAME_PROD}
