version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    command: mongod --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - '27017'

  app:
    build:
      dockerfile: Dockerfile.compose
      context: ./
    depends_on:
      - mongo
    ports:
      - '3000:3000'
      - '8080:8080'
    environment:
      NODE_ENV: development
      VITE_BASE_SERVER_URL: ${VITE_BASE_SERVER_URL}
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
      VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
      VITE_EMAIL_DOMAIN_NAME: ${VITE_EMAIL_DOMAIN_NAME}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      CODEPOCKET_CHANNEL_ID: ${CODEPOCKET_CHANNEL_ID}
      CHAPTER_FRONTED_CHANNEL_ID: ${CHAPTER_FRONTED_CHANNEL_ID}
      MONGO_DB_URI: ${MONGO_DB_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      BASE_SERVER_URL: ${BASE_SERVER_URL}
