FROM ubuntu:18.04

RUN apt-get -qq update
RUN apt-get -qq upgrade --yes
RUN apt-get -qq install curl --yes
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get -qq install nodejs --yes
RUN apt-get -qq install git --yes
RUN npm i -g yarn

WORKDIR /app

RUN yarn global add typescript

COPY . .

RUN yarn install --immutable
RUN yarn build

CMD ["yarn", "dev"]
