type: v1/appservice

images:
  apiservice:
    dockerfile: Dockerfile

services:
  app:
    class: k1.small
    image: apiservice
    ports:
      - name: http
        port: 8080
    healthcheck:
      type: http
      port: 8000
      httpPath: /

routes:
  - name: all
    protocol: http
    host:
      - scope: internal
    backend:
      - service: app
        port: http
