type: v1/appservice

images:
  server:
    dockerfile: DOCKERFILE
  db:
    buildCommand: docker-compose up -d

services:
  app:
    class: k1.nano
    image: server
    ports:
      - name: http
        port: 8000
    healthcheck:
      type: http
      port: 8000
      httpPath: /healthz

routes:
  - name: backend
    protocol: http
    host:
      - scope: internal
    backend:
      - port: http
        service: app
